name: sembast_sqflite
description: sembast NoSQL database support on top of sqflite, cross process safe database.
homepage: https://github.com/tekartik/sembast_sqflite/tree/master/sembast_sqflite
version: 2.1.1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  sembast: '>=3.4.3-4 <5.0.0'
  sqflite_common: '>=2.4.1 <4.0.0'
  meta: '>=1.3.0 <3.0.0'
  collection: '>=1.15.0 <3.0.0'
  synchronized: '>=3.0.1 <5.0.0'
dev_dependencies:
  sqflite_common_ffi: '>=2.0.0'
  test: '>=1.16.2'
  process_run: '>=0.12.0'
  pub_semver: '>=2.0.0'
  yaml: '>=3.0.0'
  lints: '>=1.0.1'
